### ISSUE TITLE
Allow multiple selections

### ISSUE THREAD

**Issue by vincode-io** [vincode-io/FeedCurator#4]

**Comment by tracure1337** [comment]
+1

**Comment by vincode-io** [comment]
@cocoonkid I did this one just for you. I'll have it uploaded to the App Store for approval today or early tomorrow.

**Comment by tracure1337** [comment]
You're a diamond!!

**Comment by vincode-io** [comment]
@cocoonkid You are running at least macOS 12, right? I need to bump the minimum version number and don't want to leave you behind.
